image: archlinux
packages:
  - git
  - wget
sources:
  - https://git.sr.ht/~ddavis/pygram11
tasks:
  - setup: |
      wget -nv http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
      bash miniconda.sh -b -p $HOME/miniconda
      source $HOME/miniconda/etc/profile.d/conda.sh
      conda config --set always_yes yes --set changeps1 no
      conda create -q -n py2 python=2.7 numpy pybind11 pytest
      conda create -q -n py3 python=3.6 numpy pybind11 pytest
  - test_python36: |
      cd pygram11
      source $HOME/miniconda/etc/profile.d/conda.sh
      conda activate py3
      pip install pip -U
      pip install .
  - test_python27: |
      cd pygram11
      source $HOME/miniconda/etc/profile.d/conda.sh
      conda activate py2
      pip install pip -U
      pip install .
