trigger:
  branches:
    include:
      - master

pr:
  - master

jobs:

- job: 'Linux'
  pool:
    vmImage: 'ubuntu-latest'
  strategy:
    matrix:
      Python27:
        python.version: '2.7'
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'

  steps:
    - template: .ci/azure-steps.yml


- job: 'macOS'
  pool:
    vmImage: 'macOS-latest'
  strategy:
    matrix:
      Python27:
        python.version: '2.7'
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'

  steps:
    - template: .ci/azure-steps.yml
