trigger:
  branches:
    include:
    - master

pr:
- master

jobs:

- job: 'Linux'
  pool:
    vmImage: 'ubuntu-latest'
  strategy:
    matrix:
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'

  steps:
  - checkout: self
    submodules: true
    displayName: 'checkout self and submodules'
  - template: .ci/azure-steps.yml


- job: 'macOS'
  pool:
    vmImage: 'macOS-latest'
  strategy:
    matrix:
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'

  steps:
  - checkout: self
    submodules: true
    displayName: 'Checkout self and submodules'
  - script: |
      set -e -x
      brew update
      brew install libomp
    displayName: 'Install libomp from Homebrew'
  - template: .ci/azure-steps.yml
