image: archlinux
packages:
- pyenv
- gcc
sources:
- https://github.com/douglasdavis/pygram11.git
tasks:
- setup: |
    pyenv install 3.7.4
    pyenv install 3.6.9
    pyenv install 2.7.16
- build: |
    cd pygram11
    eval "$(pyenv init -)"
    pyenv shell 3.7.4
    pip install pip pytest -U
    pip install .
    pyenv shell 3.6.9
    pip install pip pytest -U
    pip install .
    pyenv shell 2.7.16
    pip install pip pytest -U
    pip install .
- test: |
    eval "$(pyenv init -)"
    cd pygram11
    pyenv shell 3.7.4
    pytest --ignore=extern
    pyenv shell 3.6.9
    pytest --ignore=extern
    pyenv shell 2.7.16
    pytest --ignore=extern
triggers:
- action: email
  condition: failure
  to: "<ddavis@ddavis.io>"
