image: archlinux
packages:
- gcc
- python-pip
- python-setuptools
- python-wheel
- python-pytest
- python-numpy
sources:
- https://github.com/douglasdavis/pygram11.git
tasks:
- test: |
    cd pygram11
    python3 -m pip install .[complete] -vv
    python3 -m pytest
triggers:
- action: email
  condition: failure
  to: "<ddavis@ddavis.io>"
