image: archlinux
packages:
- python
- gcc
sources:
- https://github.com/douglasdavis/pygram11.git
tasks:
- setup: |
    curl https://pyenv.run | bash
    export PATH=$HOME/.pyenv/bin:$PATH
    eval "$(pyenv init -)"
    pyenv install 3.8.6
    pyenv install 3.7.7
    pyenv install 3.6.9
- build: |
    export PATH=$HOME/.pyenv/bin:$PATH
    eval "$(pyenv init -)"
    cd pygram11
    pyenv shell 3.8.6
    pip install pip pytest setuptools wheel -U
    pip install .
    pyenv shell 3.7.7
    pip install pip pytest setuptools wheel -U
    pip install .
    pyenv shell 3.6.9
    pip install pip pytest setuptools wheel -U
    pip install .
- test36: |
    export PATH=$HOME/.pyenv/bin:$PATH
    eval "$(pyenv init -)"
    cd pygram11
    pyenv shell 3.6.9
    pip install numpy==1.16
    python -m pytest
    pip install numpy==1.17
    python -m pytest
    pip install numpy==1.18
    python -m pytest
    pip install numpy==1.19
    python -m pytest
- test37: |
    export PATH=$HOME/.pyenv/bin:$PATH
    eval "$(pyenv init -)"
    cd pygram11
    pyenv shell 3.7.7
    pip install numpy==1.16
    python -m pytest
    pip install numpy==1.17
    python -m pytest
    pip install numpy==1.18
    python -m pytest
    pip install numpy==1.19
    python -m pytest
- test38 : |
    export PATH=$HOME/.pyenv/bin:$PATH
    eval "$(pyenv init -)"
    cd pygram11
    pyenv shell 3.8.6
    pip install numpy==1.17
    python -m pytest
    pip install numpy==1.18
    python -m pytest
    pip install numpy==1.19
    python -m pytest
triggers:
- action: email
  condition: failure
  to: "<ddavis@ddavis.io>"
