image: archlinux
packages:
- python
- gcc
sources:
- https://github.com/douglasdavis/pygram11.git
tasks:
- setup: |
    curl https://pyenv.run | bash
    export PATH=$HOME/.pyenv/bin:$PATH
    eval "$(pyenv init -)"
    pyenv install 3.8.0
    pyenv install 3.7.5
    pyenv install 3.6.9
- build: |
    export PATH=$HOME/.pyenv/bin:$PATH
    eval "$(pyenv init -)"
    cd pygram11
    pyenv shell 3.8.0
    pip install pip pytest setuptools -U
    pip install .
    pyenv shell 3.7.5
    pip install pip pytest setuptools -U
    pip install .
    pyenv shell 3.6.9
    pip install pip pytest setuptools -U
    pip install .
- test36: |
    export PATH=$HOME/.pyenv/bin:$PATH
    eval "$(pyenv init -)"
    cd pygram11
    pyenv shell 3.6.9
    pytest --ignore=extern
- test37: |
    export PATH=$HOME/.pyenv/bin:$PATH
    eval "$(pyenv init -)"
    cd pygram11
    pyenv shell 3.7.5
    pytest --ignore=extern
- test38 : |
    export PATH=$HOME/.pyenv/bin:$PATH
    eval "$(pyenv init -)"
    cd pygram11
    pyenv shell 3.8.0
    pytest --ignore=extern
triggers:
- action: email
  condition: failure
  to: "<ddavis@ddavis.io>"
