image: archlinux
packages:
  - python-pip
  - python-numpy
  - python-pytest
  - pybind11
  - twine
sources:
  - https://github.com/douglasdavis/pygram11
secrets:
  - a7bb07f9-3681-4e7e-8650-e49e3ca8c822
tasks:
  - setup: |
      echo "no setup"
  - build: |
      cd pygram11
      sudo pip install .
  - test: |
      cd pygram11
      pytest --ignore=extern
      mkdir play
      cd play
      python -c "import pygram11; print(pygram11.OPENMP)"
  - deploy: |
      cd pygram11
      python setup.py sdist
      python .ci-scripts/srht-pypi.py
triggers:
  - action: email
    condition: failure
    to: "<ddavis@ddavis.io>"
