image: debian/buster
packages:
  - git
  - wget
sources:
  - https://github.com/douglasdavis/pygram11
tasks:
  - setup: |
      wget -nv http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
      bash miniconda.sh -b -p $HOME/miniconda
      source $HOME/miniconda/etc/profile.d/conda.sh
      conda config --set always_yes yes --set changeps1 no
      conda create -q -n py37 python=3.7 numpy pytest
      conda create -q -n py38 python=3.8 numpy pytest
      conda create -q -n cf38 python=3.8 numpy pytest libgomp -c conda-forge
  - test_python37: |
      cd pygram11
      source $HOME/miniconda/etc/profile.d/conda.sh
      conda activate py37
      pip install pip -U
      pip install .
      python -m pytest
  - test_python38: |
      cd pygram11
      source $HOME/miniconda/etc/profile.d/conda.sh
      conda activate py38
      pip install pip -U
      pip install .
      python -m pytest
  - test_cf38: |
      cd pygram11
      source $HOME/miniconda/etc/profile.d/conda.sh
      conda activate cf38
      pip install pip -U
      pip install .
      python -m pytest
triggers:
  - action: email
    condition: failure
    to: "<ddavis@ddavis.io>"
