image: debian/testing
packages:
  - python3-pip
  - libgomp1
  - g++
sources:
  - https://github.com/drdavis/pygram11.git
tasks:
  - setup: |
      sudo pip3 install numpy pytest
  - build: |
      cd pygram11
      sudo pip3 install .
  - test: |
      cd pygram11
      pytest --ignore=extern
      mkdir play
      cd play
      python3 -c "import pygram11; print(pygram11.OPENMP)"
triggers:
  - action: email
    condition: failure
    to: "<ddavis@ddavis.io>"
